In [1]:
import pandas as pd

In [2]:
citibikedf = pd.read_csv('Citibike3Months.csv')

In [7]:
citibikedf.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
trip_duration          object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [8]:
citibikedf.info

<bound method DataFrame.info of                  ride_id  rideable_type     started_at       ended_at  \
0       38F943EA06A4E54F  electric_bike   3/25/23 9:20   3/25/23 9:32
1       C76EFC4C3B771E88  electric_bike   3/15/23 7:55   3/15/23 8:07
2       02C7BC83975952E6  electric_bike   3/20/23 8:50   3/20/23 9:00
3       DB0FB572E0AA9C36  electric_bike   3/2/23 10:17   3/2/23 10:27
4       A238B2BDD1072D52  electric_bike    3/4/23 9:13    3/4/23 9:25
...                  ...            ...            ...            ...
239757  9549398286BB59B5    docked_bike  5/27/23 13:24  5/27/23 13:51
239758  AB0790683044D89E   classic_bike  5/18/23 17:12  5/18/23 17:25
239759  68226FA538A405CA   classic_bike   5/5/23 18:44   5/5/23 18:56
239760  CABAC21C0F0140A5   classic_bike  5/16/23 11:56  5/16/23 12:04
239761  4AABD797EF6F7BB2   classic_bike  5/30/23 11:04  5/30/23 11:13

       trip_duration                            start_station_name  \
0            0:11:13                               Jersey & 6th St
1            0:12:03                               Jersey & 6th St
2            0:10:26                               Jersey & 6th St
3            0:10:15                               Jersey & 6th St
4            0:12:07                               Jersey & 6th St
...              ...                                           ...
239757       0:26:27  South Waterfront Walkway - Sinatra Dr & 1 St
239758       0:12:55  South Waterfront Walkway - Sinatra Dr & 1 St
239759       0:11:18  South Waterfront Walkway - Sinatra Dr & 1 St
239760       0:07:53                                Columbus Drive
239761       0:09:08  South Waterfront Walkway - Sinatra Dr & 1 St

       start_station_id end_station_name end_station_id  start_lat  start_lng  \
0                 JC027     Glenwood Ave          JC094  40.725289 -74.045572
1                 JC027     Glenwood Ave          JC094  40.725289 -74.045572
2                 JC027     Glenwood Ave          JC094  40.725289 -74.045572
3                 JC027     Glenwood Ave          JC094  40.725289 -74.045572
4                 JC027     Glenwood Ave          JC094  40.725289 -74.045572
...                 ...              ...            ...        ...        ...
239757            HB103     Newport Pkwy          JC008  40.736982 -74.027781
239758            HB103        Warren St          JC006  40.736982 -74.027781
239759            HB103        Warren St          JC006  40.736982 -74.027781
239760            JC014     Newport Pkwy          JC008  40.718355 -74.038914
239761            HB103        Warren St          JC006  40.736982 -74.027781

          end_lat    end_lng member_casual
0       40.727551 -74.071061        member
1       40.727551 -74.071061        casual
2       40.727551 -74.071061        member
3       40.727551 -74.071061        casual
4       40.727551 -74.071061        member
...           ...        ...           ...
239757  40.728745 -74.032108        casual
239758  40.721124 -74.038051        member
239759  40.721124 -74.038051        member
239760  40.728745 -74.032108        member
239761  40.721124 -74.038051        member

[239762 rows x 14 columns]>

In [9]:
citibikedf

,ride_id,rideable_type,started_at,ended_at,trip_duration,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,38F943EA06A4E54F,electric_bike,3/25/23 9:20,3/25/23 9:32,0:11:13,Jersey & 6th St,JC027,Glenwood Ave,JC094,40.725289,-74.045572,40.727551,-74.071061,member
1,C76EFC4C3B771E88,electric_bike,3/15/23 7:55,3/15/23 8:07,0:12:03,Jersey & 6th St,JC027,Glenwood Ave,JC094,40.725289,-74.045572,40.727551,-74.071061,casual
2,02C7BC83975952E6,electric_bike,3/20/23 8:50,3/20/23 9:00,0:10:26,Jersey & 6th St,JC027,Glenwood Ave,JC094,40.725289,-74.045572,40.727551,-74.071061,member
3,DB0FB572E0AA9C36,electric_bike,3/2/23 10:17,3/2/23 10:27,0:10:15,Jersey & 6th St,JC027,Glenwood Ave,JC094,40.725289,-74.045572,40.727551,-74.071061,casual
4,A238B2BDD1072D52,electric_bike,3/4/23 9:13,3/4/23 9:25,0:12:07,Jersey & 6th St,JC027,Glenwood Ave,JC094,40.725289,-74.045572,40.727551,-74.071061,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239757,9549398286BB59B5,docked_bike,5/27/23 13:24,5/27/23 13:51,0:26:27,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Newport Pkwy,JC008,40.736982,-74.027781,40.728745,-74.032108,casual
239758,AB0790683044D89E,classic_bike,5/18/23 17:12,5/18/23 17:25,0:12:55,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Warren St,JC006,40.736982,-74.027781,40.721124,-74.038051,member
239759,68226FA538A405CA,classic_bike,5/5/23 18:44,5/5/23 18:56,0:11:18,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Warren St,JC006,40.736982,-74.027781,40.721124,-74.038051,member
239760,CABAC21C0F0140A5,classic_bike,5/16/23 11:56,5/16/23 12:04,0:07:53,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
239761,4AABD797EF6F7BB2,classic_bike,5/30/23 11:04,5/30/23 11:13,0:09:08,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,Warren St,JC006,40.736982,-74.027781,40.721124,-74.038051,member